cuda: True
n_points: 
n_classes: 
wandb: False
eval: False
visualize_pc: False

experiment:
  name: "AdaPT_test"
  project: "Adapt_reloaded"
  seed: 42
  dataset: "ModelNet40"

model:
  name: "Adapt_classf"
  embed_dim: 128
  n_blocks: 4
  drop_loc: [0,1,2,3]
  drop_rate: [0.2,0.4,0.6,0.8]
  groups: 4
  sampling_met: "gumbel"
  entmax_alpha: 


train:
  lr: 0.001
  batch_size: 32
  epochs: 200
  weight_decay: 0.0001
  warmup_start: 20
  warmup_end: 40
  alpha: 1
  n_budgets: 4

